server:
  port: 8082
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin

app:
  file:
    storage-dir: "backend/file-service/file-storage"
    download-prefix: http://localhost:8888/api/v1/file/media/download/

